# http://saucelabs.com/docs/sauce-ondemand/browsers
# Default firefox
os: "Windows 2003"
browser: "firefox"
version: "3.6."
browsers: 
- - "Windows 2003"
  - "firefox"
  - "2.0."
- - "Windows 2003"
  - "firefox"
  - "3.0."
- - "Windows 2003"
  - "firefox"
  - "3.5."
- - "Windows 2003"
  - "firefox"
  - "3.6."
- - "Windows 2008"
  - "firefox"
  - "4."
- - "Windows 2003"
  - "googlechrome"
  - ""
- - "Windows 2003"
  - "iexplore"
  - "6."
- - "Windows 2003"
  - "iexplore"
  - "7."
- - "Windows 2003"
  - "iexplore"
  - "8."
# - - "Windows 2008"
#   - "iexplore"
#   - "9."
- - "Windows 2003"
  - "opera"
  - "9."
- - "Windows 2003"
  - "opera"
  - "10."
- - "Windows 2003"
  - "opera"
  - "11."
- - "Windows 2003"
  - "safari"
  - "3."
- - "Windows 2003"
  - "safari"
  - "4."
- - "Windows 2003"
  - "safariproxy"
  - "5."